### ISSUE TITLE
Citation of this work

### ISSUE THREAD

**Issue by mfurkanns** [Checkmate986212/Shot-Boundary-Detection#2]
Could you please explain where did you find this algorithm ? Can you give reference ?

**Comment by dha8102** [comment]
I'm also curious about this. I am using this algorithm in my research, which paper I should cite?

**Comment by HeliosZhao** [comment]
Hi @dha8102 and @mfurkanns
I found this algorithm and some of its code on a blog, but I cannot find it anymore. So I am sorry that I cannot provide the citation.
